version: 1.0.{build}
image: Visual Studio 2017

before_build:
- cmd: nuget restore

environment:
    COVERALLS_REPO_TOKEN:  
       secure: 6jh0dgmogwGd8epJpU3vhtJRuSNosyQYzlmNG/QadQ6OWspPtG1Lf9wgeFWPruBy

build:
  project: ConTabs.sln
  verbosity: minimal

after_test: 
# generate report for NUnit testing framework:
    - cmd:packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.2.1\tools\nunit3-console.exe" -targetargs:"/domain:single ConTabs.Tests/bin/debug/ConTabs.Tests.dll" -output:coverage.xml

# generate report for MSTest testing framework:        
    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%