version: 1.0.{build}
image: Visual Studio 2017

before_build:
- cmd: nuget restore

environment:
    COVERALLS_REPO_TOKEN:  
       secure: teIOuW1LrOWSvBgkHaDQu1ctWqA+yJyufe6YDmDrl9MMxqvCqH1C7fKo8hisScLT

build:
  project: ConTabs.sln
  verbosity: minimal

after_test: 
    # Tell OpenCover to generate coverage.xml
    - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[ConTabs]*" -target:"packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:"/domain:single ConTabs.Tests/bin/debug/ConTabs.Tests.dll" -output:coverage.xml -excludebyattribute:"System.ObsoleteAttribute"
    
    # Send coverage.xml to Coveralls
    - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml -r %COVERALLS_REPO_TOKEN%

for:
-
  branches:
    only:
      - master
  
  build:
    publish_nuget: true
    
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
  
  deploy:
    provider: NuGet
    api_key:
      secure: ghjsPlGg7R8v7U9ZYy9PxUWAJ4ijiCM/pSwXxy5eHarElGSM6gmhfdGH+EqNSsWM
    skip_symbols: false
    
- 
  branches: 
    except: 
      - master